[refactor/#125-validate-post] 게시물 validation 리팩토링
SMWU-POCHAK/POCHAK-Server pull request #126
Opened 2024-11-16 09:00 UTC by 5jisoo

## 📒 개요

게시물 관련 validation 코드 리팩토링 / 추가 하였습니닷
이거 머지되면 service test 코드 작성 고고링해볼게요~

## 📍 Issue 번호

- #125 

## 🛠️ 작업사항

- [ ]  게시물 저장 태그 수 제한 부분 리팩토링
- [ ]  게시물 태그 리스트 중복 확인 커스텀 애노테이션 추가
- [ ] 그 외 전체적으로 코드 스타일 변경

## 🧰 추가 논의사항

- 추가로 필요한 부분 있으면 의견 주십셔

2024-11-23 20:05 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/post/dto/request/PostUploadRequest.java
> +    @Size(min = 1, max = 5, message = "유저는 최대 1명 이상, 5명 이하로 태그 가능합니다.")
최대 라는 말을 빼야 하지 않나요?! 
1명 이상, 5명 이하로 태그 가능합니다 가 더 자연스러울 것 같아요

2024-11-23 20:09 UTC, dudrhy12 commented on src/test/java/com/apps/pochak/post/controller/PostControllerTest.java
> +    }
최소 1명이 태그 되어야 한다. <<를 검증할 테스트 작성은 어떤가요??

2024-12-02 10:28 UTC, yeahjinjeong requested changes

2024-12-02 10:28 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/post/service/PostService.java
>          alarmRepository.deleteByPost(post.getId());
태그된 사람도 post를 삭제할 수 있고, 해당 post와 관련된 데이터들을 다 지우는 거죠? cloudStorageService에서 postImage 지우는 것도 여기 추가해야할까요?

2024-12-02 11:38 UTC, dudrhy12 approved these changes

2024-12-02 12:08 UTC, 5jisoo commented on src/main/java/com/apps/pochak/post/service/PostService.java
>          alarmRepository.deleteByPost(post.getId());
soft delete로 구현을 해놔서 사진을 일단 저장해두어야 할 것 같아..! 스토리지에서는 삭제가 안되게 짜두긴 했슴다

2024-12-06 11:37 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/post/service/PostService.java
>          alarmRepository.deleteByPost(post.getId());
아하 나중에 30일 보관 후 영구삭제 이런식으로 구현하는 게 맞는 거 같습니당~

2024-12-06 11:37 UTC, yeahjinjeong approved these changes

2024-12-08 11:33 UTC, merged