[feat/2-profile-update] 프로필 수정 API
SMWU-POCHAK/POCHAK-Server pull request #14
Opened 2024-06-09 16:20 UTC by dudrhy12

## 📒 개요

프로필 수정 API

## 📍 Issue 번호

> #2 

## 🛠️ 작업사항

1. 자신의 프로필 수정이 가능한 API 개발
2. 프로필 수정 시, image 값 Null 예외 처리 추가
3. 프로필 수정 시, handle 값 중복 예외 처리

2024-06-10 11:31 UTC, 5jisoo requested changes
코드 스타일 생각보다 너무 잘 맞춰줘서 감동함 읽기 너무 편해요😍

2024-06-10 11:31 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/dto/response/ProfileUpdateResponse.java
> +@RequiredArgsConstructor(access = PRIVATE)
of로 name, handle, message, profileImage가 전부 들어간 Builder를 만들어 줬는데 PRIVATE으로 한 이유가 뭔가요?
추가적으로 클래스 변수들 final 처리한 이유도 궁금함다

2024-06-10 11:31 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        String profileImageUrl = awsS3Service.upload(profileUpdateRequest.getProfieImage(), MEMBER);
upload 하기 전에 기존 이미지 삭제하고 새로 업로드해줘도 좋을듯? S3 아끼기 위해 ㅎㅎ;;

2024-06-10 11:31 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        checkHandleDuplication(handle);
handle은 유니크해야하니까 아예 핸들 체크용 API를 추가적으로 만드는 것도 좋겠네여
왜 인스타그램 아예 수정 반영하기 전에 수정된 아이디 사용 가능한지 확인해주는 게 따로 있으니깐~

2024-06-10 11:31 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        final Member member = findMemberByHandle(handle);
로그인한 멤버가 수정하고자 하는 프로필과 같은지 확인하는 로직이 필요해보여요
다른 사람이 프로필을 수정하면 안되니까..ㅎㅎ

2024-06-10 11:31 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/domain/Member.java
> +    private <T> T getOrDefault(T property, T alternative){
updateMember()나 getOrDefault() 이런식으로 함수 깔끔하게 너무 좋아요🥹🥹 좋아하는 방식임ㅎㅎ
나중에 수정 기능이 post나 comment 등등으로 확장되면 BaseEntity에 옮겨도 될듯

2024-06-10 11:31 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/controller/MemberController.java
> +    public ApiResponse<?> updateProfileDetail(
여기 왜 와일드카드 타입 썼나요??

2024-06-10 11:31 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        String profileImageUrl = awsS3Service.upload(profileUpdateRequest.getProfieImage(), MEMBER);
여기서 만약에 profileImage 수정안할시에 null로 들어오면 바로 Exception 터지는 거 아닌가요?

```
public String upload(MultipartFile multipartFile, DirName dirName) {
        if (multipartFile == null)
            throw new GeneralException(NULL_FILE);
...
```

이 두 줄 추가했길래

프로필 이미지를 수정안할경우의 동작이
1. req dto 중 profileImage를 null로 전송
2. awsS3Service.upload(NULL, MEMBER)
3. Exception
4. 종료

지금 이렇게 바뀐 것 같은데
3번에서 Exception이 아니라 그냥 프로필 사진 전달 안되면 넘어가기~ 가 되어야 하지 않나 싶네요...??
-> 아니면 프로필 사진을 수정을 하던 말던 무조건 파일을 보내는 규칙으로 설정한건가?

- 잘못 이해했으면 알려주십셔

2024-06-10 11:31 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +    private void checkHandleDuplication(String handle) {
이 함수를 리포지토리로 옮겨도 될 것 같고... 
지금 보니까 findMemberByHandle 등등이랑 같이 옮겨도 될 것 같기도 하고 ,, 이건 의견 주세요

2024-07-01 01:49 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/member/dto/response/ProfileUpdateResponse.java
> +@RequiredArgsConstructor(access = PRIVATE)
요부분.. 제가 놓친 부분인 거 같아 PRIVATE 이랑 final 해제 하였습니다! 정확한 지적 감사..

2024-07-01 01:49 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        String profileImageUrl = awsS3Service.upload(profileUpdateRequest.getProfieImage(), MEMBER);
반영하였습니다><

2024-07-01 01:50 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        checkHandleDuplication(handle);
요거 새로 작업하신것 같던데 맞나요?! 그래서 관련 기존 handle 코드는 다 지웠어욥

2024-07-01 01:51 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        final Member member = findMemberByHandle(handle);
요거 한 번 코드 써보긴 했는데 .. findMemberByHandle에서 이미 해주는 작업인가? 싶더라고요....... 의견 부탁

2024-07-01 01:51 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/member/domain/Member.java
> +    private <T> T getOrDefault(T property, T alternative){
황송~🫶

2024-07-01 01:52 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/member/controller/MemberController.java
> +    public ApiResponse<?> updateProfileDetail(
다시 보니 와일드 하지 않아도 될 것 같아 고쳣음다..

2024-07-01 01:53 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        String profileImageUrl = awsS3Service.upload(profileUpdateRequest.getProfieImage(), MEMBER);
이것도!! 첨엔 무조건 파일 보낸다는 생각으로 코드를 썼는데 다시 생각해보니 그냥 전달 안되어도 넘어가기~ 가 더 적합한 것 같아 넘어가도록 수정해보았읍니다

2024-07-01 03:25 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        checkHandleDuplication(handle);
넹 맞아요~~

2024-07-01 03:36 UTC, 5jisoo requested changes

2024-07-01 03:36 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        if (loginMember.equals(updateMember)) {
엇 이거 조건이 앞에 `!` 이게 붙어야할 것 같은디?? loginMember랑 updateeMember랑 같으면 넘어가는 거고 아니면 에러 터지는 거니깐~

아 그리고 handle로 멤버 찾는 메서드가 여러개가 있는데,,,, (리팩토링이 굉장히 필요해보이지만) memberRepository에 findMemberByHandleWithoutLogin이였나 그 메소드 있거든용? 그거 써보삼,,, 저 메소드는 아마 차단 로직 들어가 있는 메소드일거에요,,,,.. 이건 나중에 네이밍을 고쳐봄ㅜ 아니면 좋은 네이밍 아이디어 있으면 고쳐주세요

2024-07-01 03:36 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        awsS3Service.deleteFileFromS3(updateMember.getProfileImage());
기존 프로필 사진을 삭제하는 코드가 65번째 줄 if 문 뒤로 가야할 것 같음
```java
if (profileUpdateRequest.getProfieImage() != null) { // 만약 이미지 수정 요청이 들어오면
    awsS3Service.deleteFileFromS3(updateMember.getProfileImage()); // 그 때 기존 이미지를 삭제한다
    profileImageUrl = awsS3Service.upload(profileUpdateRequest.getProfieImage(), MEMBER); // 그리고 새로운 이미지를 업로드한다
}
```

2024-07-01 03:59 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        if (loginMember.equals(updateMember)) {
헐 큰일날뻔
메소드도 함 써볼게여

2024-07-01 03:59 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        awsS3Service.deleteFileFromS3(updateMember.getProfileImage());
ㅎ,,,맞네요 ㅎ;;ㅎㅎ;;

2024-07-01 10:51 UTC, 5jisoo approved these changes
오케이 전부 확인했습니당~

2024-07-01 10:51 UTC, merged