Feat/#130 alarm auto delete
SMWU-POCHAK/POCHAK-Server pull request #143
Opened 2024-12-09 01:55 UTC by dudrhy12

## 📒 개요

생성된지 30일이 지난 알람은 매 정각마다 삭제되는 스케줄러를 도입하였습니다.

## 📍 Issue 번호

- #139 

## 🛠️ 작업사항

- [ ] Scheduler 작성
- [ ] Repo 작성

## 🧰 추가 논의사항

- Test.. 하면 삭제되는데 할까요..

2024-12-09 05:38 UTC, 5jisoo requested changes

2024-12-09 05:38 UTC, 5jisoo commented on src/main/java/com/apps/pochak/alarm/domain/repository/AlarmRepository.java
태그 알람은 제외시키는 거 아니었나요?? 아 그리고 JPQL이 아닌 네이티브 쿼리로 작성한 이유도 궁금합니다

2024-12-09 06:03 UTC, 5jisoo commented on src/main/java/com/apps/pochak/alarm/domain/repository/AlarmRepository.java
아 지금 다시 보니까 확인하지 않은 알람도 제외하는 것 같아요.

2024-12-16 11:05 UTC, 5jisoo commented
스케줄러 테스팅도 가능한가요? 테스트 코드 있으면 좋을 것 같은데, 작성 예정인지 궁금합니다~

2024-12-22 17:43 UTC, dudrhy12 commented
ClockConfig가 https://github.com/SMWU-POCHAK/POCHAK-Server/pull/153#issue-2752122067 해당 PR에 올라와있어 제외하고 commit 했습니다!

2024-12-23 01:07 UTC, 5jisoo commented on src/test/java/com/apps/pochak/alarm/service/AlarmSchedulerTest.java
> +        alarmDeletionScheduler.deleteExpiredAlarms();
근데 이렇게 호출을 하면 앞에서 시간 설정할 필요가 없지 않나요??

2024-12-23 01:08 UTC, 5jisoo commented on src/test/java/com/apps/pochak/alarm/service/AlarmSchedulerTest.java
> +        alarmDeletionScheduler.deleteExpiredAlarms();
이거 스케줄러 테스트 지금 계속 시도는 해보고 있는데 호출이 최선인가 고민중

2024-12-23 03:13 UTC, 5jisoo requested changes

2024-12-23 03:13 UTC, 5jisoo commented on src/test/java/com/apps/pochak/alarm/service/AlarmSchedulerTest.java
> +        ReflectionTestUtils.setField(alarmDeletionScheduler, "clock", clock);
이렇게 private field 고치는 게 mock bean 주입보다 나을까요? 전 후자로 하긴 함

2024-12-23 03:13 UTC, 5jisoo commented on src/test/java/com/apps/pochak/alarm/service/AlarmSchedulerTest.java
> +        Alarm expiredAlarm = AlarmFixture.STATIC_COMMENT_REPLY_ALARM;
왜 이건 alarmRepository에 저장을 안하는건가요?

2024-12-23 03:13 UTC, 5jisoo commented on src/test/java/com/apps/pochak/alarm/service/AlarmSchedulerTest.java
> +        ReflectionTestUtils.setField(alarmDeletionScheduler, "clock", clock);
105 - 114에서 60일 이후로 시간 변경해서 expiredAlarm, tagAlarm, uncheckedAlarm을 저장하고
124 - 132에서 20일 이후로 시간 변경해서 recentAlarm을 저장한 의도가 뭔가요?

expiredAlarm, tagAlarm, uncheckedAlarm 이랑 recentAlarm 의 createdDate를 각각 60일 이후, 20일 이후로 설정하고자..?

2024-12-23 03:13 UTC, 5jisoo commented on src/test/java/com/apps/pochak/alarm/service/AlarmSchedulerTest.java
> +        ReflectionTestUtils.setField(alarmDeletionScheduler, "clock", clock);
근데 의아한게 60일 이후, 20일 이후면 미래..라서 만료되어 삭제되면 안되지 않나요?

2024-12-30 11:50 UTC, 5jisoo commented on src/test/java/com/apps/pochak/alarm/service/AlarmSchedulerTest.java
> +        member1 = memberRepository.save(STATIC_MEMBER1);
여기서 member1, member2 .. post1, post2. ... 등등을 저장해주는 이유가 뭔가요?? 알람이랑 연결되어 있어서인가요?

2025-01-05 15:56 UTC, dudrhy12 commented on src/test/java/com/apps/pochak/alarm/service/AlarmSchedulerTest.java
> +        member1 = memberRepository.save(STATIC_MEMBER1);
맞습니다! 알람 저장하기 전에 저장되어야 하는 객체들이라 @BeforeEach로 선언해서 저장해주고 있슴다

2025-01-09 05:57 UTC, yeahjinjeong approved these changes

2025-02-08 09:18 UTC, 5jisoo reviewed
update로 deleted 상태를 저장해두는 거면 deleteExpiredAlarms() 한 다음에, findAll() 하면 3개(expiredAlarm, tagAlarm, uncheckedAlarm)이 전부 나오는데, expiredAlarm만 deleted상태로 남아있어야하는거 아닌가여?

2025-02-09 01:39 UTC, dudrhy12 commented
저희 Alarm Entity에 @SQLRestriction("status = 'ACTIVE'") 이 설정이 되어 있어서 findAll() 해도 status=ACTIVE인 알람만 찾아오기 때문에 findAll() 하면 tagAlarm, uncheckedAlarm 두 개만 가져오는걸로 알고 있음다

2025-02-09 01:40 UTC, dudrhy12 commented
> update로 deleted 상태를 저장해두는 거면 deleteExpiredAlarms() 한 다음에, findAll() 하면 3개(expiredAlarm, tagAlarm, uncheckedAlarm)이 전부 나오는데, expiredAlarm만 deleted상태로 남아있어야하는거 아닌가여?

저희 Alarm Entity에 @SQLRestriction("status = 'ACTIVE'") 이 설정이 되어 있어서 findAll() 해도 status=ACTIVE인 알람만 찾아오기 때문에 findAll() 하면 tagAlarm, uncheckedAlarm 두 개만 가져오는걸로 알고 있음다

2025-02-09 04:29 UTC, 5jisoo approved these changes

2025-02-09 04:29 UTC, merged