[feat/#35-profile-alarm-update] 프로필 수정 시, 사진 삭제 스케줄러 추가
SMWU-POCHAK/POCHAK-Server pull request #43
Opened 2024-09-01 16:15 UTC by dudrhy12

## 📒 개요

프로필 수정 시에 기존 사진을 즉시 수정하지 않고, 스케줄러를 통해 5분마다 한 번에 삭제하여 성능을 개선한다.

## 📍 Issue 번호

> #35 

## 🛠️ 작업사항

- 사진 삭제 전용 큐와 스케줄러 추가
- 배치 테스트 완료

## 🧰 변경로직

- 기존 프로필 수정 시에 즉시 삭제 처리되어 있던 로직을 삭제하였습니다.

2024-09-02 06:09 UTC, 5jisoo requested changes
몇가지 고려하면 더 좋을 것들이랑 궁금한 점들 남겨뒀습니다~
그리고 저도 더 생각해보니 batch 보단 scheduler가 더 맞는 것 같아서 클래스 이름 변경이 필요할 것 같습니다 (다른 의견 있으면 남기삼요)
패키지 구성은 더 생각해봐야될 것 같은데 아예 scheduler 디렉터리를 member 아래에 만드는건 어떨지..?

2024-09-02 06:09 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/ProfileImageCleanupBatch.java
> +public class ProfileImageCleanupBatch {
큐와 네이밍을 동일하게 하려면
`ProfileImageDeletionBatch` 등으로 네이밍 변경하면 더 좋을 것 같아요

2024-09-03 16:33 UTC, 5jisoo requested changes

2024-09-03 16:33 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/scheduler/ProfileImageDeletionBatch.java
> +                if ("NoSuchKey".equals(e.getErrorCode())) {
이 "NoSuchKey"는 문자열말고 변수쓰는 방식으로 변경하는게 나을것같아요

2024-09-03 16:33 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/scheduler/ProfileImageDeletionBatch.java
> +                    //log 남기기
주석 앞에 TODO: 붙이면 나중에 확인 쉬움요

2024-09-03 16:33 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/scheduler/ProfileImageDeletionBatch.java
> +                if ("NoSuchKey".equals(e.getErrorCode())) {
그 외에 자주 쓰이는 에러 코드를 아예 enum..등으로 정리해서 여기가 아니라 deleteFileFromS3()에서 GeneralException을 상속한 커스텀 exception을 던지게 하는게 맞는 것 같아요

2024-09-03 16:33 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/scheduler/ProfileImageDeletionQueue.java
> +    public void ProfileImageDeletionQueueWhenServerShutDown() {
이 메소드가 서버 닫히기 전에 정리해주는 건가요?

2024-09-03 16:36 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/scheduler/ProfileImageDeletionBatch.java
> +                if ("NoSuchKey".equals(e.getErrorCode())) {
그리고 이런 에러코드.. 작업할때 공식문서 한번씩만 코멘트에 추가해주세요~
https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#S3OutpostsErrorCodeList

2024-09-03 17:11 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/scheduler/ProfileImageDeletionQueue.java
> +    public void ProfileImageDeletionQueueWhenServerShutDown() {
메소드 대문자로 시작합니다~ 고쳐야함

2024-09-14 04:22 UTC, 5jisoo requested changes

2024-09-14 04:22 UTC, 5jisoo commented on src/main/java/com/apps/pochak/alarm/service/Scheduler/AlarmProfileUpdateScheduler.java
> +        LocalDateTime recentTime = LocalDateTime.now().minusMinutes(10);
위에 주석은 5분 근데 now().minusMinutes(10) ?? 5분인가요 10분인가요?

2024-09-14 04:22 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/domain/repository/MemberRepository.java
> +    List<Member> findRecentProfileUpdates(@Param("recentTime") LocalDateTime recentTime);
s3 사진 날리는 건 스택을 썼는데 Member 업데이트에서는 DB에서 찾아준 이유..?가 궁금해요
s3에서도 이렇게 꺼내서 쓰거나 member에서도 스택을 쓰거나..해도 되지 않나여?

2024-09-14 04:22 UTC, 5jisoo commented on src/main/java/com/apps/pochak/alarm/service/Scheduler/AlarmProfileUpdateScheduler.java
> +        for (Member member : recentProfileUpdates) {
이렇게 반복문을 돌리면 한사람당 쿼리가 8번(조회 4번 + 수정 4번)씩 나가는건데...
(이렇게 구현할거면 조회하고 -> 더티체킹으로 수정 방법보단 바로 수정 쿼리를 날리는게 좋은 것 같기도 하네요?)
다른 로직이나 쿼리를 짜보는게 맞는 것 같아요

애초에 구현하고자 했던 batchUpdate랑은 좀 멀어보이는... 코드네요🥲
in 쿼리 사용하는 방향으로 생각해보는건 어떨까요?

2024-09-14 04:22 UTC, 5jisoo commented on src/main/java/com/apps/pochak/alarm/service/Scheduler/AlarmProfileUpdateScheduler.java
> +    private <T extends Alarm> void updateAlarmsProfileInfo(List<T> alarmsToUpdate, Member updatedMember) {
이거 메소드 자체가 이미 더티체킹이 해주는 과정이라.. 없..~어도 되지 않나요?

2024-09-16 14:27 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/alarm/service/Scheduler/AlarmProfileUpdateScheduler.java
> +        LocalDateTime recentTime = LocalDateTime.now().minusMinutes(10);
.. 조금 안전하게 2배수로 했어여
스케줄러는 5분마다 돌아가지만 바뀐 프로필은 최근 10분간의 기록을 찾게 >> 요거 커밋 메세지에 그래서 10분 적당한지 물어보는거 써있습니다

2024-10-04 12:57 UTC, closed without merging