[feature/#54-memories] 추억 페이지 프리뷰 API
SMWU-POCHAK/POCHAK-Server pull request #60
Opened 2024-09-22 18:50 UTC by yeahjinjeong

## 📒 개요

추억 페이지 프리뷰

## 📍 Issue 번호

> #54 
> #59 

## 🛠️ 작업사항

- 아직 예외처리 전 입니다
- 변수 정하는 게 어려웠어요
- 테스트는 쿼리가 잘 되는지 도통 감이 안와서 냅다 했습니다
- 컨트롤러 테스트 전이에요! 머지 하면 안 될듯 ... 조언 부탁 ...

## 🧰 변경로직

- 내용을 적어주세요.

2024-09-23 06:47 UTC, 5jisoo requested changes
1. 추억페이지
2. 내가 포착된 페이지
3. 같이 포착된 페이지
4. 내가 포착해준 페이지

이렇게 총 네 페이지가 있는데 이걸 한번에 구현하신걸로 보여요! 

근데 2, 3, 4 페이지는 각각 따로 페이징이 필요해서..
한번에 DTO로 보내는게 아닌 1, 2, 3, 4 각각 따로 API를 만들어보는건 어떨까요??

2024-09-23 06:47 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/controller/MemoriesController.java
> +@RequestMapping("api/v2/memories")
v1으로 해도 괜찮을 것 같습니다ㅎㅎ

2024-09-23 06:47 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        Page<Tag> tagged = tagRepository.findFirstTag(member, loginMember, PageRequest.of(0, 1));
지금 페이지가 상수 처리되어 있는데 2번째, 3번째 페이지는 어떻게 요청해야하죠??

2024-09-23 06:47 UTC, 5jisoo commented on src/test/java/com/apps/pochak/tag/domain/repository/TagRepositoryTest.java
> +        Member owner = Member.signupMember()
이런건 fixture 같은거 활용해도 좋을 것 같아요ㅎㅎ 미리 만들어둔게 좀 있습니다

2024-09-23 06:51 UTC, yeahjinjeong commented
네 페이지 중에 1번만 한 것 입니닷 젤 첫번째꺼랑 최근꺼 게시물 하나씩만 가져오는거라서 페이징은 상수로 들어갔어요

2024-09-23 06:51 UTC, yeahjinjeong commented on src/test/java/com/apps/pochak/tag/domain/repository/TagRepositoryTest.java
> +        Member owner = Member.signupMember()
헙 찾아보겠습니다

2024-09-23 06:52 UTC, 5jisoo commented
Spring REST Docs의 자동 API 문서화를 위해서는 Controller 테스트가 꼭! 필요한데 서비스, 레포지토리의 테스트와는 분리해서 작성하고 있어요! (서비스, 레포는 mock처리함)
아마 다른 controllertest 코드가 많아서 참고할 부분은 많아보여요! 

참고: https://spring.io/projects/spring-restdocs

2024-09-23 06:53 UTC, 5jisoo commented
> 네 페이지 중에 1번만 한 것 입니닷 젤 첫번째꺼랑 최근꺼 게시물 하나씩만 가져오는거라서 페이징은 상수로 들어갔어요

앗 제가 착각했네요ㅎㅎ 머쓱 ~ 다시 한번봐볼게요

2024-09-23 07:09 UTC, 5jisoo requested changes
몇가지 궁금한 것들 더 남겨두었습니다~~!

2024-09-23 07:09 UTC, 5jisoo commented on src/main/java/com/apps/pochak/tag/domain/repository/TagRepository.java
> +    select distinct t1
여기서 distinct가 필요한 경우가 잘 안떠오르네요 붙인 이유가 궁금해요

2024-09-23 07:09 UTC, 5jisoo commented on src/main/java/com/apps/pochak/tag/domain/repository/TagRepository.java
> +    or (t.member = :loginMember and p.owner = :member))
둘이 같이 태그된 순간의 경우에도 최근에 들어가야하지 않을까요?? 이건 디스코드에서 기준에 대해 좀 더 논의해도 좋을 것 같아요

2024-09-23 07:11 UTC, 5jisoo commented
아 그리고 date형식은 아마 LocalDate로 줘도 될..것 같긴한데 프론트에 한번 여쭤봐야될 것 같아요ㅎㅎ

2024-09-23 07:14 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/tag/domain/repository/TagRepository.java
> +    select distinct t1
셀프조인해가지고, 두명이 함께 태그된 게시물이 중복으로 걸릴까봐 했습니다

2024-09-23 08:13 UTC, 5jisoo commented on src/main/java/com/apps/pochak/tag/domain/repository/TagRepository.java
> +    select distinct t1
근데 그 where 절에서 
```
and t1.member = :loginMember
and t2.member = :member
```
이거 줘서 상관없지 않나요??

2024-09-26 07:45 UTC, 5jisoo requested changes
제가 함수로 빼는 것에 좀 집착을..해서 전부 고치실 필요는 없고 읽어보시고 필요해보이는 것만 바꿔보시면 좋을 것 같습니다ㅎㅎ

읽어보면서도 배운 느낌이네요! 
Controller 테스트 코드도 작성해서 올려주세요!

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        final Long countTag = tagRepository.countByPost_PostStatusAndPost_OwnerAndMember(PostStatus.PUBLIC, loginMember, member);
오.. 쿼리메소드의 달인이시네요😮 찾아보니 _ 이게 JOIN이라고는 하는데 어떻게 해석하면 되는 거죠..?
- post status가 PUBLIC한 post를 tag랑 JOIN
- owner가 `loginmember`이고, member는 `member`인 member 엔티티를 또 JOIN

이게 맞을까욤

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        final Page<Tag> tagged = tagRepository.findTagByMember(member, loginMember, PageRequest.of(0, 1));
이 메소드랑 다른 메소드들도 owner랑 member를 조건으로 둔다면 findTagBy**MemberAndOwner** 이런식으로 이름 짓는게 맞는 것 같기도 하네요

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        final Page<Tag> tagged = tagRepository.findTagByMember(member, loginMember, PageRequest.of(0, 1));
뭔가 member랑 owner의 위치가 좀 헷갈리는 느낌이라서요! 의견일 뿐입니닷

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        final Page<Tag> taggedWithAsc = tagRepository.findTaggedWith(loginMember, member, PageRequest.of(0, 1, Sort.by(Sort.Direction.ASC, "post.allowedDate")));
와 이거 Sort.by 쓰는 것도 정말 깔끔하네요 메소드 재사용성이 정말 굿..

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        final Tag latestTagOrTagged = (tagOrTagged.hasContent() ? tagOrTagged.getContent().get(0) : null);
지금 여기 다섯줄이 뭔가 같은걸 반복하고 있는 것 같아서 함수로 빼는게 가독성에도 좋아보일 것 같아요

`x.hasContent() ? x.getContent().get(0) : null`
위에서 x 부분만 바뀌고 있는 거니까욥

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        }
```java
        Tag latestTag = null;
        if (latestTaggedWith != null && latestTagOrTagged != null) {
            latestTag = latestTaggedWith.getPost().getAllowedDate().isAfter(latestTagOrTagged.getPost().getAllowedDate()) ? latestTaggedWith : latestTagOrTagged;
        } else if (latestTaggedWith == null && latestTagOrTagged != null) {
            latestTag = latestTagOrTagged;
        } else if (latestTaggedWith != null) {
            latestTag = latestTaggedWith;
        }
```

그리고 이부분은 함수로 빼는 것은 어떤가요? 조금 극단적일 수는 있으나 findLatestTag() 와 같은 네이밍?으로요
if-else 문이 뭔가 이 메소드의 주된 흐름과는 조금 동떨어져 보인다는 생각이 들듯말듯 하네요 허허

(제 스타일일 수도 있는데 그냥 단순한 의견이니 그대로 냅두셔도 됩니다)

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        }
아니면 이부분을 함수로 빼도 될것 같아요

```java
latestTaggedWith.getPost().getAllowedDate().isAfter(latestTagOrTagged.getPost().getAllowedDate()) ? latestTaggedWith : latestTagOrTagged;
```

옆으로 코드가 너무 길면 읽기가 불편하고 .() .() 이게 반복되니 의도 파악이 어려운 것 같아요! 뭔가 메소드로 뺀 뒤에 메소드 명을 통해 좀 의도를 전달해보는 건 어떨까요..??

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
> +        this.followDay = (followDate.isAfter(followedDate) ? Period.between(LocalDate.now(), followDate.toLocalDate()).getDays() : Period.between(LocalDate.now(), followedDate.toLocalDate()).getDays(
줄이 너무 길어서 로직은 맞아 보이는데 여기도 함수로 빼면 좋을 것 같아요! 
그리고 이건 프엔이랑도 상의를 해봐야하긴 하지만 프엔에서 계산해도 될 것 같기도하고.. 그렇네요 (어차피 LocalDateTime을 넘기니까요!)

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
> +        this.pochakCount = countTag.intValue();
이거 그냥 Long 으로 보내도 될 거에요 ! 아마 그냥 NUMBER 타입이 될..걸..요??

2024-09-26 07:45 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
> +        this.pochakCount = countTag.intValue();
Long 타입을 int로 바꿔서 보낸건 없긴 한데 
지금 찾아보니 DTO가 뭐는 int로 보내고 Long으로 보내고 있었네요;; 통일시키면 좋을 것 같아요,,ㅎ

2024-09-26 08:09 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        final Long countTag = tagRepository.countByPost_PostStatusAndPost_OwnerAndMember(PostStatus.PUBLIC, loginMember, member);
이게 조건 명시라고 하더라고요 Post의 PostStatus랑 Post의 Owner과 Member
Tag가 Post랑 Member를 가지고 있어서 알아서 조인해주는 것 같아요

작업 하면서 Tag가 Post를 갖는 게 맞는지, Post가 Tag를 갖는 게 맞는지 생각이 들더라고요
PostRepo 보니까 Tag로 Post를 찾을 때도 있고 저처럼 TagRepo에서 Tag찾아도 어차피 Post 넘기는 거라서 이 두개가 통일되면 재사용성을 좀 높일 수 있지 않나 하는 생각을 했습니다. 근데 Tag가 Post를 갖고있는데 Tag로 조인해서 Post를 찾는 게 부자연스럽지 않나 ..? 싶기도 했습니다. 지금 바꾸기엔 뭔가 많이 손대야 할 것 같아서 그대로 두는 게 최선일수도 있겠네요..
```
    @Query("""
    select p from Post p
    join Tag t on t.post = p and t = :tag
    join fetch p.owner
    where p.status = 'ACTIVE'
    """)
    Optional<Post> findPostByTag(@Param("tag") final Tag tag);

2024-09-26 08:33 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        final Long countTag = tagRepository.countByPost_PostStatusAndPost_OwnerAndMember(PostStatus.PUBLIC, loginMember, member);
오.. 저는 뭔가 태그된 멤버랑 게시물 정보가 둘 다 필요할 때(조건절에 들어가거나 할 때) TagRepo 사용해서 쿼리 날렸던 것 같은데,
뭔가 countBy"Post" 인데 TagRepo에 있는게 좀 어색해보이기도 하네요🧐
아니면 아예 커스텀 레포를 하나 만드는 것도 방법일 것 같구요.. 이건 리팩토링 이슈를 새롭게 파서 고민해봐도 좋을 것 같아요

2024-09-26 08:37 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +        final Long countTag = tagRepository.countByPost_PostStatusAndPost_OwnerAndMember(PostStatus.PUBLIC, loginMember, member);
여기서는 countBy"Post_PostStatus"And"Post_Owner"And"Member"예요!

2024-09-26 11:40 UTC, 5jisoo requested changes

2024-09-26 11:40 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
> +            final Tag latestTag) {
정말 사소한데 이런 부분은

```java
@Builder(builderMethodName = "of")
    public MemoriesPreviewResponse(
            final Member loginMember,
            final Member member,
            final Follow follow,
            final Follow followed,
            final Long countTag,
            final Long countTaggedWith,
            final Long countTagged,
            final Tag firstTagged,
            final Tag firstTag,
            final Tag firstTaggedWith,
            final Tag latestTag // enter
) {
```

이렇게 엔터를 추가하긴 했어요!

2024-09-26 11:40 UTC, 5jisoo commented on src/test/java/com/apps/pochak/tag/domain/repository/TagRepositoryTest.java
> +        Tag tag = Tag.builder()
Post나 Tag도 기존 Fixture 사용해도 될 것 같은데 일부러 새로 만드신건가요??

2024-09-26 11:40 UTC, 5jisoo commented on src/main/java/com/apps/pochak/memories/service/MemoriesService.java
> +    private Tag pageToTag(final Page<Tag> tagPage) {
이것처럼 Page중에서 가장 첫번째 원소 꺼내는거 전역 메소드로 빼는 건 어떨까요?? 디스코드에 더 자세하게 남겨뒀슴다

2024-09-26 14:00 UTC, yeahjinjeong commented on src/test/java/com/apps/pochak/tag/domain/repository/TagRepositoryTest.java
> +        Tag tag = Tag.builder()
같이 태그되는 거는 fixture에 없어서 새로 만들었던 것 같아요 Fixture에 추가하고 쓸까요?

2024-09-26 14:01 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
> +            final Tag latestTag) {
깔끔하군요👍👍

2024-09-27 01:19 UTC, 5jisoo requested changes
테스트는 잘 돌아가는 것 같아요!!
`src/docs/asciidoc` 에 들어가보면 AsciiDoc파일이 있슴다 그것도 만들어야 html파일이 생겨요!!
memory.adoc파일 만들어주시고 index.adoc파일의 맨 아래 목차에 추가해주십셔

2024-09-28 04:30 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/fixture/PostFixture.java
> +    public static final Post PUBLIC_POST_FOR_TAG = new Post(
아 이거 그리고 저도 쓸 것 같아서 ㅋㅋㅋㅋㅎ 혹시 네이밍 `POST_WITH_MULTI_TAG` 이런식으로 변경가능할까요??

2024-09-28 04:30 UTC, 5jisoo commented on src/test/java/com/apps/pochak/tag/fixture/TagFixture.java
> +    public static final Tag APPROVED_TAG1 = new Tag(
이것도 네이밍을 1, 2 이것보다.. 뭔가 어떤 게시물이랑 연결되어 있는건지 드러나는 이름이면.. 좋을 것 같슴다

2024-09-28 08:25 UTC, 5jisoo approved these changes
굿! 수고하셨습니다 세 개의 API를 순식간에 해치우셨네요🤭

2024-09-28 09:40 UTC, dudrhy12 approved these changes

2024-09-28 13:05 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/memories/dto/response/MemoriesPreviewResponse.java
> +    private MemoriesElement firstPochackedWith;
아하 firstBonded도 좋을 것 같네요~

2024-09-28 13:07 UTC, merged