[Fix/#53-alarm-db-update] Alarm 엔티티 구조 변경
SMWU-POCHAK/POCHAK-Server pull request #72
Opened 2024-09-28 06:25 UTC by dudrhy12

## 📒 개요

alarm 관련 DB 구조 변경

## 📍 Issue 번호

- #53 

## 🛠️ 작업사항

- [ ] Alarm Entity 구조 변경
- [ ] Alarm Element 구조 변경

## 🧰 추가 논의사항

- 현재 구조 괜찮으면 관련해서 Alarm 로직들 살펴보고 문제 없으면 Merge 하고 배치 작업 다시 들어가도록 하겠습니다!

2024-09-28 06:53 UTC, 5jisoo requested changes

2024-09-28 06:53 UTC, 5jisoo commented on src/main/java/com/apps/pochak/alarm/domain/Alarm.java
> +    private Long senderId;
이거 Member ManyToOne으로 FK 연결 어떤가요?

2024-09-28 06:53 UTC, 5jisoo commented on src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/CommentAlarmElement.java
> +    private Long senderId;
이거 dto 바뀐거면 API 스펙이 바뀐거라,, 프엔에도 바로 전달해야될 것 같아요

2024-09-28 06:58 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/alarm/dto/response/alarm_element/CommentAlarmElement.java
> +    private Long senderId;
하압...... 스펙은 안바뀌는게 좋으니까...... 안바뀌는 방향으로 다시 고려해보겠씁니다

2024-09-28 06:59 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/alarm/domain/Alarm.java
> +    private Long senderId;
오케 좋아요

2024-09-30 09:36 UTC, yeahjinjeong approved these changes

2024-09-30 11:03 UTC, 5jisoo approved these changes
굿!!

2024-09-30 11:06 UTC, merged