Refactor: querydsl로 리팩토링 및 테스트 코드 작성 #80
SMWU-POCHAK/POCHAK-Server pull request #83
Opened 2024-10-04 03:16 UTC by yeahjinjeong

## 📒 개요

jpql과 페이징처리부분이 다릅니다

## 📍 Issue 번호

- #80 

## 🛠️ 작업사항

- [ ] querydsl
- [ ] 테스트
- [ ] 성능 개선

## 🧰 추가 논의사항

주석해놓은걸 추천받았으나, 테스트할 때 getTotalPage가 정확하게 나오지 않아서(왜 일까요) `fetch().size()`로 구현했습니다.
쿼리에서 `select(post.count())`를 쓰는 게 부하가 더 적을 것 같긴해서 더 고민해보겠습니다.. ㅠㅠ 

references 
- https://hstory0208.tistory.com/entry/QueryDSL-%ED%8E%98%EC%9D%B4%EC%A7%95-%EC%B2%98%EB%A6%AC
- https://junuuu.tistory.com/549
`fetch().size()`
- https://jaeseo.tistory.com/entry/Pageable-%EC%BB%A4%EC%8A%A4%ED%85%80-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%ACfeat-PageableDefault
페이지네이션 예외처리 관련
- https://velog.io/@youngerjesus/%EC%9A%B0%EC%95%84%ED%95%9C-%ED%98%95%EC%A0%9C%EB%93%A4%EC%9D%98-Querydsl-%ED%99%9C%EC%9A%A9%EB%B2%95
페이징 성능을 위해 no offset 사용하기

2024-10-04 06:00 UTC, 5jisoo commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +        LongSupplier count = () -> content.fetch().size();
이렇게 해결하면 깔끔한데 노션에 작성하신 것처럼 결국 애플리케이션으로 전부 가져와서 조립해주는 형태라..
위험할 것 같은 느낌...?🫤

2024-10-04 13:09 UTC, 5jisoo requested changes

2024-10-04 13:09 UTC, 5jisoo commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +    public JPAQuery<Post> findUploadPost(
이건 private으로 설정하는게 좋지 않을까요??

2024-10-04 13:09 UTC, 5jisoo commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +                .where(post.in(findUploadPost(ownerId, loginMemberId)));
으음...ㅜ 저도 이게 한계긴 했는데 더 나은 방법 없겠죠?🥲

2024-10-04 13:09 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
이 테스트는 그냥 구현 확인에 중점을 둔건가요?? 뭔가 owner가 차단했을때, 아니면 현재 로그인한 사람이 차단했을때, .. 등등 다양한 케이스를 테스트하면 좋을 것 같아서요

2024-10-04 13:09 UTC, 5jisoo commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +                .where(
이건 저도 보다가 생각났는데, 순서를 진짜 실행순서대로 where -> groupby -> having으로 두면 더 좋을 것 같아요ㅎ 저도 고치겠슴다

2024-10-04 13:09 UTC, 5jisoo commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +            final Long ownerId,
이건 스타일 차이라서 무시하셔도 됨다
MemberService에서 Member의 Owner를 어차피 찾으니까 Member owner로 받아도 될.. 것 같지 않나요? ㅎㅎ

2024-10-06 04:08 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +    public JPAQuery<Post> findUploadPost(
넹~🤗 테스트하고 바꾼다는게 ~

2024-10-06 04:09 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +                .where(post.in(findUploadPost(ownerId, loginMemberId)));
where in 안 하고 해봤는데 그거는 카운트가 이상해서 이렇게 하는 게 맞는 거 같아요!! 👍👍

2024-10-06 04:12 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +                .where(
아하 맞네요

2024-10-06 04:49 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +            final Long ownerId,
오우좋아요

2024-10-06 10:49 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        assertThat(posts.getContent().get(0)).isEqualTo(savedPostData.getSavedPost());
Post 엔티티에 equals 오버라이딩 안해두긴 했는데 작동 되나요??

2024-10-06 10:54 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
>          final Member loginMember = memberRepository.findMemberById(accessor.getMemberId());
아 그리고 이거 으음 이게 한번더 체킹해주니까 안전할 것 같긴해서 좀 고민이.. 되긴 한데ㅜ 
accessor에서 복호화해서 바로 memberId 뽑아주니까 그냥 findMemberById는 지우고 accesor.getMemberId()해서 바로 메소드로 전달하는건 어때여?

2024-10-07 04:13 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/member/service/MemberService.java
>          final Member loginMember = memberRepository.findMemberById(accessor.getMemberId());
에 그러네요!

2024-10-07 04:15 UTC, yeahjinjeong commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        assertThat(posts.getContent().get(0)).isEqualTo(savedPostData.getSavedPost());
equals 오버라이딩이 필요한가요?! assertThat 메소드인걸로 알고있어요

2024-10-07 04:49 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/member/service/MemberService.java
>          final Member loginMember = memberRepository.findMemberById(accessor.getMemberId());
아 근데 이부분은 다른 서비스들에서도 다 member객체로 넘겨서 고민이네요 이부분만 memberId 쓰는 게 확장성 생각하면 굳이 싶은 것 같기두 하구 ... 그래요

2024-10-07 10:55 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        assertThat(posts.getContent().get(0)).isEqualTo(savedPostData.getSavedPost());
이게 Member.java에 있는 건데 Post엔 없어서요ㅎㅎ.. JPA가 equals 보장을 해준다고는 들었는데 흠냐 돌아가면 상관 없을 것 같아요! 

전 기존에 이게 없어서 expected post랑 actual post를 id 비교로 했는데 저게 더 나아보이네요ㅎㅎ 

```java
    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null) {
            return false;
        }
        if (this.getClass() != o.getClass()) {
            return false;
        }

        Member member = (Member) o;
        return Objects.equals(id, member.id);
    }
```

2024-10-07 10:56 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
>          final Member loginMember = memberRepository.findMemberById(accessor.getMemberId());
그렇긴해요 근데 필요없는 쿼리라는 생각이 들어서,, 허허
안그래도 예전에 한번 대대적으로 필요없이 member 한 번 찾는 걸 고치려고 하긴 해서,, 흐음..~  고민되네요

2024-10-07 11:03 UTC, yeahjinjeong commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        assertThat(posts.getContent().get(0)).isEqualTo(savedPostData.getSavedPost());
아 ~~~ 이거는 객체 비교 메소드네요 맞아요 그 내부 데이터가 같으면 같은 객체로 검증해주나보네요 돌아가긴합니다~

2024-10-07 11:04 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        assertThat(posts.getContent().get(0)).isEqualTo(savedPostData.getSavedPost());
아하 그렇다면 좋슴다😊

2024-10-07 11:04 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        blockRepository.save(new Block(
이렇게 반복되는거 저는 메소드로 따로 빼놓긴 했는데 참고하면 좋을 것 같아욥

2024-10-07 11:05 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        blockRepository.save(new Block(
https://github.com/SMWU-POCHAK/POCHAK-Server/pull/84#issuecomment-2395412190

2024-10-08 04:23 UTC, yeahjinjeong commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        blockRepository.save(new Block(
요거는 머지되면 바꿀게요! 충돌날 거 같아서

2024-10-08 04:30 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/member/service/MemberService.java
>          final Member loginMember = memberRepository.findMemberById(accessor.getMemberId());
`final Member owner = memberRepository.findByHandle(handle, loginMember);`
근데 이 밑에 여기에서 Member를 넘겨줘야해서 어차피 멤버를 찾긴 해야할 것 같아요
아니면 멤버 레포 리팩토링까지 해야할 것 같네요

2024-10-08 04:32 UTC, 5jisoo commented on src/main/java/com/apps/pochak/member/service/MemberService.java
>          final Member loginMember = memberRepository.findMemberById(accessor.getMemberId());
아 그럼 나중에 저거 리팩토링하면서 고치는게 맞을 것 같아요! 👍

2024-10-08 04:33 UTC, 5jisoo approved these changes
수고하셨슴다😊

2024-10-09 16:14 UTC, dudrhy12 approved these changes

2024-10-10 04:35 UTC, 5jisoo commented
제 PR이랑 조금 컨플릭 나는 것 같아요! 컨플릭 해결하고 머지하십셔

2024-10-10 06:34 UTC, merged