[Refactor/#94-findTaggedPost()] `findTaggedPost()` QueryDSL로 리팩토링
SMWU-POCHAK/POCHAK-Server pull request #99
Opened 2024-10-14 03:30 UTC by dudrhy12

## 📒 개요

`findTaggedPost()` QueryDSL로 리팩토링
## 📍 Issue 번호

- #94 

## 🛠️ 작업사항

- [ ] 기존 `findTaggedPost()` PostCustomRepo로 이동
- [ ] QueryDSL로 리팩토링
- [ ] 테스트 코드

## 🧰 추가 논의사항

- 아직 테스트 코드는 작성 중입니다!
- 최대한 메소드 재사용성을 높였는데 과하진 않은지 궁금합니다.

2024-10-14 03:31 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +                        .and(checkPublicPost()))
```
                .join(tag).on(tag.post.eq(post)
                        .and(tag.member.eq(member))
                        .and(checkPublicPost()))
```

이부분이 postList랑 postCount에 동일하게 2번 사용이 되는데 메소드로 따로 뺄지.. 고민입니다.
딱히 기능을 나타내는 부분은 아니지만.. 또 2번 사용이 되고 있으니까

2024-10-16 01:05 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/member/service/MemberService.java
> +        final Page<Post> taggedPost = postCustomRepository.findTaggedPost(member, loginMember.getId(), pageable);
loginMember를 가져오지않고 `accessor.getId()` 사용하는 것도 좋아보입니다~

2024-10-21 06:25 UTC, 5jisoo commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +    private JPAQuery<Post> findTaggedPost(
private 메소드 아래로 내려주세요!

2024-10-21 06:28 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
테스트 케이스 중에서 비정상적인 경우 외에도,
정상적으로 조회되는지 확인하는 코드도 필요해 보입니닷

2024-10-21 09:38 UTC, yeahjinjeong approved these changes

2024-10-27 18:25 UTC, dudrhy12 commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +            final Member taggedMember,
이거 taggedMember로 할지,, owner로 할지,, 무한굴레에 빠졌습니다

2024-11-05 11:40 UTC, yeahjinjeong commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +            final Member taggedMember,
taggedMember가 좋지않을까요?!

2024-12-02 12:06 UTC, 5jisoo requested changes
몇가지 수정 필요한 부분 남겨두었습니다~

2024-12-02 12:06 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        assertEquals(post.getId(), postPage.getContent().get(0).getId());
```java
assertFalse(postPage.getContent().isEmpty()); // 필요 없음
assertEquals(1, postPage.getTotalElements());
```

위 줄이랑 아래 줄이 동일한 내용을 확인하는 것 같아서 위 코드는 필요 없을 것 같습니다~

2024-12-02 12:06 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        block(taggedMember, loginMember);  // 태그된 멤버에게 차단당함
중간중간 주석들은 헷갈려서... 인가요??

2024-12-02 12:06 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +    void findTaggedPost_WhenNoBlock() throws Exception {
메소드명 뒤 쪽에 _WhenNoBlock()은 필요 없을 것 같기도 하고.. 이건 취향 차이일 것 같기도 해요

2024-12-02 12:06 UTC, 5jisoo commented on src/main/java/com/apps/pochak/post/domain/repository/PostCustomRepository.java
> +    private JPAQuery<Post> findTaggedPost(
이거 아직 수정 안된건가요?

2024-12-02 12:06 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Post post = savePost(owner, loginMember);
```java
Post post = savePost(owner, loginMember);
```
savePost() 메소드 보시면 태그된 멤버가 두번째.. 세번째 인자로 들어가야 하는데 loginMember 가 들어가있네요..!

2024-12-02 12:06 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Post post = savePost(owner);  // 게시글을 저장
여기는 아예 태그된 멤버가 없고..

2024-12-02 12:06 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Post post = savePost(owner, loginMember);
아래 savePost() 파라미터 명 보시면 taggedMemberList로 들어가있습니다~ 참고

2024-12-09 01:48 UTC, dudrhy12 commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Post post = savePost(owner, loginMember);
이거 게시글 주인에게 로그인 멤버가 차단당한거니까
로그인 멤버가 게시글에 태그된걸로 생각해서 두번째 인자를 loginMember로 한거에요! 혹시 의도가.. 좀 불분명할까요?

2024-12-09 05:57 UTC, 5jisoo requested changes
`findTaggedPost_WhenBlockedByPostOwner`메소드에 대한 질문 남겨두었고,
몇가지 인자 전달에 실수가 있었던 것 같아 코멘트 남겨두었습니다

2024-12-09 05:57 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Post post = savePost(owner, loginMember);
아래 `findTaggedPost_WhenBlockedByTaggedMember` 메소드와 동일하게 이 테스트케이스가 아래를 테스트하고자 하는 것 아닌가요?
1. owner가 현재 로그인 멤버가 아닌 다른 사람을 태그하여 게시물을 올림.
2. owner에게 현재 로그인 멤버가 차단당함.
3. 로그인 멤버가 (차단당하지 않은) 태그된 다른 사람들의 프로필에 pochaked탭을 조회했을 때 owner에게 차단당한 게시물은 제외하고 보여짐

> 이게 아니면 무엇을 테스트하고자 한건지.. 댓글 좀..

만약에 그렇다면.. 애초에 게시물 주인에게 로그인 멤버가 태그된 상태에서 게시물 주인이 태그된 멤버를 차단했으면 해당 게시물은 INACTIVE처리가 돼요.
owner가 loginMember를 차단하였는지에 대한 여부와 해당 게시물이 제외되어 조회되었는지의 여부랑은 상관없어지는거죠.

2024-12-09 05:57 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +                owner,
지금 loginMember를 태그해서 POCHAKED 탭을 조회하는 거..라고 하셨는데 여기서 왜 인자를 owner로 전달하죠??
그래서 아래 테스트들도 통과한 것 같아요.

2024-12-09 05:57 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +                owner,
여기서도 taggedMember를 태그하여 업로드하였는데 인자로 owner를 전달하네요

2024-12-09 08:00 UTC, dudrhy12 commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Post post = savePost(owner, loginMember);
지수님이 작성해준 로직이 제 의도가 맞아요! INACTIVE로 바뀌는걸 놓쳤네요 해당 테스트 메소드는 삭제하도록 하겠습니다

2024-12-16 11:08 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
owner에게 차단당하였거나 / 차단한 경우..도 테스트해야하지 않을까요..?

2024-12-30 06:24 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Page<Post> postPage_notBlocked = postCustomRepository.findTaggedPostPage(
?? 이건 무슨 의도인가요? findTaggedPostPage() 정상 작동하는지 확인하는 테스트가 있어서... 확인 안해도 되지 않을까요?

2024-12-30 06:24 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +    @DisplayName("[프로필 POCHAKED 탭 조회] 게시글의 주인에게 차단 당하였다면 해당 게시물은 제외되어 조회된다.")
loginMember가 owner를 블락한 테스트 케이스는 따로 없는걸까요??

2024-12-30 11:42 UTC, dudrhy12 commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Page<Post> postPage_notBlocked = postCustomRepository.findTaggedPostPage(
태그한 멤버에게는 포스트가 잘 보이고 블락한 멤버에게는 포스트가 안보이는거 같이 테스트 한겁니다!

2024-12-30 11:44 UTC, dudrhy12 commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +    @DisplayName("[프로필 POCHAKED 탭 조회] 게시글의 주인에게 차단 당하였다면 해당 게시물은 제외되어 조회된다.")
loginMember가 owner를 블락하면 post가 inactive되지 않나요?? 블락 쿼리 봤을 때 그렇게 확인했어서 스킵했는데 혹 제가 이해한 것과 다른가요??

2024-12-30 11:45 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Page<Post> postPage_notBlocked = postCustomRepository.findTaggedPostPage(
두번째 경우가 자신이 자신의 프로필을 확인한건데.. 먼가 테스트 의도는 차단 여부와 상관있는지? 를 확인하는 것 같은데 차단 여부랑은 크게 막 상관있는 것 같지는 않아서요! (자기자신을 블락할 수는 없으니..)
어차피 정상 테스트도 있으니까 이 경우는 확인 안해도 되지 않을까하는 생각이 들긴 듭니다요..? 아니면 차라리 차단을 당하지 않은 제 3자가 확인한다던가.. 근데 이경우도 정상 테스트가 있어서.. 흠냐링

2024-12-30 11:50 UTC, dudrhy12 commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +        Page<Post> postPage_notBlocked = postCustomRepository.findTaggedPostPage(
흠 테스트 네이밍을 POCHAKED로 해두어서 맞는 말이네요 저부분만 삭제할게요!

2024-12-30 11:52 UTC, 5jisoo commented on src/test/java/com/apps/pochak/post/domain/repository/PostCustomRepositoryTest.java
> +    @DisplayName("[프로필 POCHAKED 탭 조회] 게시글의 주인에게 차단 당하였다면 해당 게시물은 제외되어 조회된다.")
오잉? loginMember가 post에 태그되었을때는 .. inactive가 되겠죠..? 근데 여기서는 아니지 않나요?

2025-01-09 06:56 UTC, 5jisoo approved these changes

2025-01-13 11:10 UTC, merged